### ISSUE TITLE
Don't work on OS X

### ISSUE THREAD

**Issue by fazibear** [marciogm/asdf-crystal#1]
On OS X
```
$ asdf install crystal 0.20.5
```

```
dyld: Library not loaded: /usr/local/opt/libevent/lib/libevent-2.0.5.dylib
  Referenced from: /Users/fazibear/.asdf/installs/crystal/0.20.5/embedded/bin/crystal
  Reason: image not found
/Users/fazibear/.asdf/installs/crystal/0.20.5/bin/crystal: line 102: 79582 Trace/BPT trap: 5       "$INSTALL_DIR/embedded/bin/crystal" "$@"
```

same with

```
$ asdf install crystal ref:0.20.5
```

**Comment by marciogm** [comment]
Are you using homebrew?
`brew install libevent `
or `brew unlink libevent && brew link libevent`

**Comment by fazibear** [comment]
The versions don't match. This one is from brew:
```
libevent: stable 2.1.8 (bottled)
Asynchronous event library
http://libevent.org
Conflicts with: pincaster
/usr/local/Cellar/libevent/2.1.8 (847 files, 2.2M) *
  Poured from bottle on 2017-01-31 at 13:56:38
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libevent.rb
==> Dependencies
Build: autoconf ✔, automake ✔, doxygen ✔, libtool ✔, pkg-config ✔
Required: openssl ✔
```

**Comment by marciogm** [comment]
Seems `libevent` are in conflict with `pincaster`, maybe it's provides a older version of `libevent` in your formula.
Can you see if you already have `libevent` installed?

**Comment by fazibear** [comment]
Just like I said I have installed `2.1.8` which is newer than crystal is linked with.

**Comment by fazibear** [comment]
You need to relink it with this command:

```
install_name_tool -change /usr/local/opt/libevent/lib/libevent-2.0.5.dylib @executable_path/libevent.dylib embedded/bin/crystal
```

**Comment by marciogm** [comment]
About shards, you are able to run with `crystal deps`.
or are you getting errors on this?

**Comment by fazibear** [comment]
But there is no way to run `shards build`. Shards should be also in path.

**Comment by marciogm** [comment]
Neither `crystal deps build` or `crystal deps init`?
Because shards are distributed with Crystal.

**Comment by fazibear** [comment]
Any progress on relinking ?

**Comment by fazibear** [comment]
Version `0.21.0` work well without relinking.
